version: "latest"
services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  backend-1:
    container_name: backend-1
    build:
      context: ./backend-1
      dockerfile: ./Dockerfile
  backend-2:
    container_name: backend-2
    build:
      context: ./backend-2
      dockerfile: ./Dockerfile